name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # O la rama que uses

# Permisos necesarios para que la acción de GitHub Pages funcione
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # O 'yarn' si usas Yarn

      - name: Install dependencies
        run: npm ci # O 'yarn install --frozen-lockfile' si usas Yarn

      - name: Build with prerender
        run: npm run build # Asegúrate de que este comando ejecute 'react-router build'

      - name: Create 404.html fallback
        run: cp build/client/index.html build/client/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/client # Directorio de salida de React Router

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
